# Generated by Django 5.2.6 on 2025-11-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnectlysite', '0002_rename_industry_sectors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='economic_highlight',
        ),
        migrations.RemoveField(
            model_name='country',
            name='economic_highlight_link',
        ),
        migrations.RemoveField(
            model_name='country',
            name='fdi_trend',
        ),
        migrations.RemoveField(
            model_name='country',
            name='free_trade_agreements',
        ),
        migrations.RemoveField(
            model_name='country',
            name='investment_climate',
        ),
        migrations.RemoveField(
            model_name='country',
            name='labor_cost_usd',
        ),
        migrations.RemoveField(
            model_name='country',
            name='median_age',
        ),
        migrations.RemoveField(
            model_name='country',
            name='political_stability_index',
        ),
        migrations.RemoveField(
            model_name='country',
            name='primary_revenue_source',
        ),
        migrations.RemoveField(
            model_name='country',
            name='trade_access_score',
        ),
        migrations.AddField(
            model_name='country',
            name='economic_highlights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='fdi_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='gross_national_income',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='labor_force_participation',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='merchandise_trade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='political_stability_percentile',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='trade_rating',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='value_of_exports',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='value_of_imports',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='exchange_rate_to_usd',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='gdp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='gdp_growth_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='political_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='population_growth_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='tariff_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='investmentpathway',
            name='investment_pathway_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='investmentpathway',
            name='investment_pathway_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='investmentpathway',
            name='investment_pathway_3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sectors',
            name='economic_contribution_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sectors',
            name='growth_trend',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sectors',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name='DataLinks',
        ),
    ]
