# Generated by Django 5.2.6 on 2025-11-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnectlysite', '0004_alter_country_exchange_rate_to_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
