"""
Scripting initially used to convert DB diagram to django-python ready model class. Not needed in the end.
"""

import re
from pathlib import Path

# Path to SQL DB Diagram
SQL_FILE = Path("database_schema.sql")
OUTPUT_FILE = Path("models.py")

# Map SQL types → Django field types
TYPE_MAP = {
    "int": "models.IntegerField()",
    "bigint": "models.BigIntegerField()",
    "decimal": "models.DecimalField(max_digits=15, decimal_places=2)",
    "varchar": "models.CharField(max_length=255)",
    "text": "models.TextField()",
}


def parse_foreign_keys(sql):
    """
    Extract foreign key references as a dict:
    {table_name: {column_name: referenced_table}}
    """
    fks = {}
    fk_pattern = (
        r'ALTER TABLE "(\w+)" ADD FOREIGN KEY \("(\w+)"\) REFERENCES "(\w+)" \("id"\);'
    )
    matches = re.findall(fk_pattern, sql)
    for table, col, ref_table in matches:
        if table not in fks:
            fks[table] = {}
        fks[table][col] = ref_table
    return fks


def convert_sql_to_django(sql):
    tables = re.findall(r'CREATE TABLE "(\w+)" \((.*?)\);', sql, re.S)
    foreign_keys = parse_foreign_keys(sql)

    output = [
        "from django.db import models\n",
        "# --- AUTO GENERATED FROM dbdiagram.io schema with foreign keys ---\n\n",
    ]

    for table_name, body in tables:
        model_name = table_name  # use original capitalization
        output.append(f"class {model_name}(models.Model):\n")
        lines = [line.strip() for line in body.split(",\n")]

        for line in lines:
            if not line or "PRIMARY KEY" in line or "GENERATED BY DEFAULT" in line:
                continue

            parts = line.split()
            col_name = parts[0].replace('"', "")
            col_type = parts[1].lower()

            # Check if this column is a foreign key
            fk_table = foreign_keys.get(table_name, {}).get(col_name)
            if fk_table:
                output.append(
                    f"    {col_name} = models.ForeignKey('{fk_table}', on_delete=models.CASCADE)\n"
                )
                continue

            # Handle VARCHAR(n)
            if "varchar" in col_type:
                length = re.search(r"\((\d+)\)", col_type)
                max_len = length.group(1) if length else "255"
                django_field = f"models.CharField(max_length={max_len})"
            # Handle DECIMAL(a,b)
            elif "decimal" in col_type:
                digits = re.search(r"\((\d+),(\d+)\)", col_type)
                if digits:
                    django_field = f"models.DecimalField(max_digits={digits.group(1)}, decimal_places={digits.group(2)})"
                else:
                    django_field = (
                        "models.DecimalField(max_digits=15, decimal_places=2)"
                    )
            # Other types
            else:
                django_field = TYPE_MAP.get(
                    col_type.split("(")[0], "models.TextField()"
                )

            output.append(f"    {col_name} = {django_field}\n")

        output.append("\n")
    return "".join(output)


def main():
    sql = SQL_FILE.read_text()
    django_models = convert_sql_to_django(sql)
    OUTPUT_FILE.write_text(django_models)
    print(f"✅ Django models with ForeignKeys generated at: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
